{
 "title": "Grafana k6 - Apdex Overview",
 "description": "Apdex Overview",
 "tags": [
  "prometheus",
  "k6",
  "apdex"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   { "name": "T", "label": "[T]arget time (seconds) Apdex", "query": "0.1" }
  ]
 },
 "panels": [
  { "title": "Apdex Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "# Apdex\n\n[Apdex](https://en.wikipedia.org/wiki/Apdex) (_Application Performance Index_) allows us to monitor end-user satisfaction. \nIt is an open industry standard that estimates the end user’s satisfaction level on an application’s response time through a score between 0 and 1.\n\nThe Apdex score is calculated based on your required SLA (_Service-Level Agreement_) where you can define a response time threshold of T seconds, where all responses handled in T or less seconds satisfy the end user."
   }
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(histogram_fraction($T, $T*4, (k6_http_req_duration_seconds{expected_response=\"true\"}))*histogram_count(k6_http_req_duration_seconds{expected_response=\"true\"}) + (histogram_fraction(0, $T, (k6_http_req_duration_seconds{expected_response=\"true\"}))*histogram_count(k6_http_req_duration_seconds{expected_response=\"true\"})/2))/\nhistogram_count(k6_http_req_duration_seconds{})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(histogram_fraction($T, $T*4, (k6_http_req_duration_seconds{expected_response=\"true\"}))*histogram_count(k6_http_req_duration_seconds{expected_response=\"true\"}) + (histogram_fraction(0, $T, (k6_http_req_duration_seconds{expected_response=\"true\"}))*histogram_count(k6_http_req_duration_seconds{expected_response=\"true\"})/2))/\nhistogram_count(k6_http_req_duration_seconds{})",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Satisfied requests",
   "type": "bargauge",
   "description": "**Satisfied:** Response time less than or equal to T seconds.",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_fraction(0, $T, (k6_http_req_duration_seconds{expected_response=\"true\"}))*histogram_count(k6_http_req_duration_seconds{expected_response=\"true\"})>0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Tolerating requests",
   "type": "bargauge",
   "description": "-   **Tolerating:** Response time between T seconds and 4T seconds.",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_fraction($T, $T*4, (k6_http_req_duration_seconds{expected_response=\"true\"}))*histogram_count(k6_http_req_duration_seconds{expected_response=\"true\"})>0",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Frustrating requests",
   "type": "bargauge",
   "description": "**Frustrating:** Response time greater than 4 T seconds + Failed.",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_fraction($T*4, 9999999, (k6_http_req_duration_seconds{expected_response=\"true\"}))*histogram_count(k6_http_req_duration_seconds{expected_response=\"true\"})>0",
     "legendFormat": "{{name}}"
    },
    {
     "expr": "histogram_count(k6_http_req_duration_seconds{expected_response=\"false\"})>0",
     "legendFormat": "{{name}}"
    }
   ]
  }
 ]
}