{
 "title": "Grafana k6 - Custom Metrics",
 "description": "Grafana k6 - Custom Metrics Example",
 "tags": [
  "prometheus",
  "k6",
  "custom-metrics"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" },
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "## Custom Metrics in k6 for Grafana\n\nK6 is a powerful performance testing tool, and one of its strengths is the ability to create custom metrics tailored to your testing needs.\n\n### Types of Custom Metrics:\n1. **Counter**: Measures a cumulative value. E.g., total number of specific errors.\n2. **Gauge**: Represents a single value, which can increase or decrease. E.g., the number of concurrent users.\n3. **Trend**: Records and analyzes the distribution of a series of values over time. E.g., response times.\n4. **Rate**: Measures the rate of success compared to the total number of events. E.g., error rates.\n\n### Example:\nTo create a custom counter metric:\n```javascript\nimport { Counter } from 'k6/metrics';\nlet myCounter = new Counter('my_counter_name');\n```\n\n\n\n### Using with Grafana:\nAfter running a k6 test that records custom metrics, you can visualize the results in Grafana. Just integrate k6 with a supported backend (e.g., Prometheus) and then use the Grafana dashboard to display the metrics.\n\n_Source: [k6 Custom Metrics Documentation](https://k6.io/docs/using-k6/metrics/create-custom-metrics/)_"
   }
  },
  { "title": "Example Custom Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Counter",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "k6_my_counter_total{}", "legendFormat": "{{testid}}" }
   ]
  },
  {
   "title": "Gouge",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    { "expr": "k6_my_gauge{}", "legendFormat": "{{testid}}" }
   ]
  },
  {
   "title": "Rate",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "avg(k6_my_rate_rate{})", "legendFormat": "{testid}}" }
   ]
  },
  {
   "title": "Trends",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    { "expr": "k6_my_trend{}", "legendFormat": "{{testid}}" }
   ]
  }
 ]
}