{
 "title": "k6 Prometheus (Native Histograms)",
 "description": "Visualize k6 OSS results stored in Prometheus with Native Histogram. K6_PROMETHEUS_RW_TREND_AS_NATIVE_HISTOGRAM option must be true. ",
 "tags": [
  "prometheus",
  "k6",
  "native-histogram"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Prometheus DS", "query": "prometheus" },
   { "name": "testid", "label": "Test ID", "query": { "query": "label_values(testid)" } },
   { "name": "quantile", "label": "Quantile", "query": "0.99" },
   { "name": "adhoc_filter", "label": "AdhocFilter" }
  ]
 },
 "panels": [
  {
   "title": "Performance Overview",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(k6_vus{testid=~\"$testid\"})",
     "legendFormat": "vus"
    },
    {
     "expr": "histogram_quantile($quantile, sum by (le) (rate(k6_http_req_duration_seconds{testid=~\"$testid\"}[$__rate_interval])))",
     "legendFormat": "http_req_duration_q$quantile"
    },
    {
     "expr": "sum(irate(k6_http_reqs_total{testid=~\"$testid\"}[$__rate_interval]))",
     "legendFormat": "http_req_s"
    },
    {
     "expr": "sum(irate(k6_http_reqs_total{testid=~\"$testid\", expected_response=\"false\"}[$__rate_interval]))",
     "legendFormat": "http_req_s_errors"
    }
   ]
  },
  {
   "title": "Performance Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP requests",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 0, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(k6_http_reqs_total{testid=~\"$testid\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "HTTP request failures",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 6, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(k6_http_reqs_total{testid=~\"$testid\", expected_response=\"true\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Peak RPS",
     "type": "stat",
     "gridPos": { "h": 3, "w": 6, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(irate(k6_http_reqs_total{testid=~\"$testid\"}[$__rate_interval]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "HTTP Request Duration",
     "type": "stat",
     "description": "Select a different quantile to change the query",
     "gridPos": { "h": 3, "w": 6, "x": 18, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, sum by(le) (rate(k6_http_req_duration_seconds{testid=~\"$testid\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Transfer Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "avg(irate(k6_data_sent_total{testid=~\"$testid\"}[$__rate_interval]))",
       "legendFormat": "data_sent"
      },
      {
       "expr": "avg(irate(k6_data_received_total{testid=~\"$testid\"}[$__rate_interval]))",
       "legendFormat": "data_received"
      }
     ]
    },
    {
     "title": "Iterations",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, sum by(le) (rate(k6_iteration_duration_seconds{testid=~\"$testid\"}[$__rate_interval])))",
       "legendFormat": "iteration_duration_q$quantile"
      },
      {
       "expr": "avg(k6_dropped_iterations_total{testid=~\"$testid\"})",
       "legendFormat": "dropped_iterations"
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "HTTP Latency Timings",
     "type": "timeseries",
     "description": "Select a different quantile to change the query\n\n<a href=\"https://k6.io/docs/using-k6/metrics/reference/#http\" target=\"_blank\">HTTP-specific built-in metrics</a>",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, sum by(le) (rate(k6_http_req_blocked_seconds{testid=~\"$testid\"}[$__rate_interval])))",
       "legendFormat": "http_req_blocked_q$quantile"
      },
      {
       "expr": "histogram_quantile($quantile, sum by(le) (rate(k6_http_req_tls_handshaking_seconds{testid=~\"$testid\"}[$__rate_interval])))",
       "legendFormat": "http_req_tls_handshaking_q$quantile"
      },
      {
       "expr": "histogram_quantile($quantile, sum by(le) (rate(k6_http_req_sending_seconds{testid=~\"$testid\"}[$__rate_interval])))",
       "legendFormat": "http_req_sending_q$quantile"
      },
      {
       "expr": "histogram_quantile($quantile, sum by(le) (rate(k6_http_req_waiting_seconds{testid=~\"$testid\"}[$__rate_interval])))",
       "legendFormat": "http_req_waiting_q$quantile"
      },
      {
       "expr": "histogram_quantile($quantile, sum by(le) (rate(k6_http_req_receiving_seconds{testid=~\"$testid\"}[$__rate_interval])))",
       "legendFormat": "http_req_receiving_q$quantile"
      },
      {
       "expr": "histogram_quantile($quantile, sum by(le) (rate(k6_http_req_duration_seconds{testid=~\"$testid\"}[$__rate_interval])))",
       "legendFormat": "http_req_duration_q$quantile"
      }
     ]
    },
    {
     "title": "HTTP Latency Stats",
     "type": "timeseries",
     "description": "Select a different quantile to change the query",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($quantile, sum by (le) ((rate(k6_http_req_duration_seconds{testid=~\"$testid\"}[$__rate_interval]))))",
       "legendFormat": "http_req_duration_q$quantile"
      },
      {
       "expr": "histogram_quantile($quantile, sum by(le) (rate(k6_http_req_waiting_seconds{testid=~\"$testid\", expected_response=\"true\"}[$__rate_interval])))",
       "legendFormat": "success_http_req_duration_q$quantile"
      },
      {
       "expr": "histogram_quantile($quantile, sum by(le) (rate(k6_http_req_waiting_seconds{testid=~\"$testid\", expected_response=\"false\"}[$__rate_interval])))",
       "legendFormat": "errors_http_req_duration_q$quantile"
      }
     ]
    },
    {
     "title": "HTTP Request Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(irate(k6_http_reqs_total{testid=~\"$testid\"}[$__rate_interval]))",
       "legendFormat": "http_req_s"
      },
      {
       "expr": "sum(irate(k6_http_reqs_total{testid=~\"$testid\", expected_response=\"false\"}[$__rate_interval]))",
       "legendFormat": "http_req_s_errors"
      },
      {
       "expr": "sum(irate(k6_http_reqs_total{testid=~\"$testid\", expected_response=\"true\"}[$__rate_interval]))",
       "legendFormat": "http_req_s_success"
      }
     ]
    },
    {
     "title": "Requests by URL",
     "type": "table",
     "description": "min/max/p95/p99 depends on the available Quantile Stats",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "histogram_quantile(0, sum by(le, name, method, status) (rate(k6_http_req_duration_seconds{testid=~\"$testid\"}[$__rate_interval])))",
       "legendFormat": "min"
      },
      {
       "expr": "histogram_quantile(1, sum by(le, name, method, status) (rate(k6_http_req_duration_seconds{testid=~\"$testid\"}[$__rate_interval])))",
       "legendFormat": "max"
      },
      {
       "expr": "histogram_quantile(0.95, sum by(le, name, method, status) (rate(k6_http_req_duration_seconds{testid=~\"$testid\"}[$__rate_interval])))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum by(le, name, method, status) (rate(k6_http_req_duration_seconds{testid=~\"$testid\"}[$__rate_interval])))",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Checks",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Checks list",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "round(k6_checks_rate{testid=~\"$testid\"}, 0.1)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Checks Success Rate (aggregate individual checks)",
     "type": "timeseries",
     "description": "Filter by check name to query a particular check",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "%" } },
     "targets": [
      {
       "expr": "avg(round(k6_checks_rate{testid=~\"$testid\"}, 0.1)*100)",
       "legendFormat": "k6_checks_rate"
      }
     ]
    }
   ]
  }
 ]
}